name: bosun
description: A library for parsing CLI input and structuring CLI commands
version: 0.0.2
repository: https://www.github.com/pyrestudios/bosun

environment:
  sdk: '>=2.15.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
